apiVersion: v1
kind: Service
metadata:
  name: flights-api
  labels:
    name: flights-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: flights-api
---
apiVersion: v1
kind: Service
metadata:
  name: flights-api-v1
  labels:
    name: flights-api-v1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: flights-api
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-api-v1
  labels:
    app: flights-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-api
      version: v1
  template:
    metadata:
      labels:
        app: flights-api
        version: v1
    spec:
      containers:
        - image: "briaracr.azurecr.io/hackfest/flights-api:1.0"
          imagePullPolicy: Always
          name: flights-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.tracker.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.tracker.svc.cluster.local:3006/       
          ports:
          - containerPort: 3003
            protocol: TCP
      restartPolicy: Always