---
# Source: quakes-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quakes-api
  labels:
    name: quakes-api
spec:
  type: "LoadBalancer"
  ports:
  - name: http
    port: 3012
    targetPort: 3012
  selector:
    app: quakes-api
---
# Source: quakes-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "quakes-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakes-api
  template:
    metadata:
      labels:
        app: quakes-api
    spec:
      containers:
        - image: "briaracr.azurecr.io/hackfest/quakes-api:1.0"
          imagePullPolicy: Always
          name: quakes-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.tracker.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.tracker.svc.cluster.local:3006/       
          ports:
          - containerPort: 3012
            protocol: TCP
      restartPolicy: Always
