apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
    name: flights-api
    namespace: tracker
spec:
    service: flights-api
    backends:
    - service: flights-api-v1
      weight: 90
    - service: flights-api-canary
      weight: 10