apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-api
  version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-api
      version: v1
  template:
    metadata:
      labels:
        app: flights-api
        version: v1
    spec:
      containers:
        - image: "briaracr.azurecr.io/hackfest/flights-api:1.0"
          imagePullPolicy: Always
          name: flights-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.tracker.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.tracker.svc.cluster.local:3006/       
          ports:
          - containerPort: 3003
            protocol: TCP
      restartPolicy: Always
