apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: flights-api
  namespace: hackfest
spec:
  provider: linkerd
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flights-api
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 3003
    # container port number or name (optional)
    targetPort: 3003
  canaryAnalysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 70
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    # Linkerd Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 30s
    # testing (optional)
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.hackfest/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -s http://flights-api-canary.hackfest:3003/status | grep payload"
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.hackfest/
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 http://flights-api.hackfest:3003/status"