apiVersion: v1
kind: Service
metadata:
  name: quakes-api
  labels:
    name: quakes-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3012
    targetPort: 3012
  selector:
    app: quakes-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakes-api
  template:
    metadata:
      labels:
        app: quakes-api
    spec:
      containers:
        - image: chzbrgr71/quakes-api:v1.1
        #- image: docker.pkg.github.com/chzbrgr71/service-tracker/quakes-api:v1.1
          imagePullPolicy: Always
          name: quakes-api
          env:
            - name: DATA_SERVICE_URI
              value: http://data-api.tracker.svc.cluster.local:3009/
          ports:
          - containerPort: 3012
            protocol: TCP
      restartPolicy: Always
