apiVersion: v1
kind: Service
metadata:
  name: service-tracker-ui
  labels:
    name: service-tracker-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: service-tracker-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "service-tracker-ui"
spec:
  selector:
    matchLabels:
      app: service-tracker-ui
  template:
    metadata:
      labels:
        app: service-tracker-ui
    spec:
      containers:
        - image: chzbrgr71/service-tracker-ui:v1.1
        #- image: docker.pkg.github.com/chzbrgr71/service-tracker/service-tracker-ui:v1.1
          imagePullPolicy: Always
          name: service-tracker-ui
          resources:
            requests:
              memory: "512Mi"
              cpu: "1.0"
            limits:
              memory: "1024Mi"
              cpu: "2.0"
          env:
            - name: FLIGHT_API_ROOT
              value: http://flights-api.tracker.svc.cluster.local:3003/
            - name: WEATHER_API_ROOT
              value: http://weather-api.tracker.svc.cluster.local:3015/
            - name: QUAKES_API_ROOT
              value: http://quakes-api.tracker.svc.cluster.local:3012/
          ports:
          - containerPort: 8080
            protocol: TCP
      restartPolicy: Always        
